[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "github.com/lestrrat-go/config"
  branch = "master"

[[constraint]]
  name = "github.com/lestrrat-go/envload"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=>1.2.2"
